/* GymTrack — ÜBUNGS-DATENBANK
 *
 * Reines Datenmodul, keine Logik ausser der i18n-Registrierung ganz unten.
 * Laedt VOR app-streak.js (dort liegt die Bibliotheks-UI: openExLibrary/renderExLibrary).
 *
 * Schema pro Eintrag:
 *   n  Name (deutsch) — zugleich De-facto-ID: PLAN_TEMPLATES.libNames, Plan-Import und
 *      die "vorhanden"-Pruefung matchen ueber diesen String. NIE bestehende Namen aendern.
 *   e  Emoji
 *   mg Muskelgruppen-ID aus MUSCLE_GROUPS ('brust'|'ruecken'|'beine'|'arme'|'schultern'|'core')
 *      oder '' = ohne Muskelgruppe (Cardio/Kondition, eigener Bibliotheks-Filter "Cardio")
 *   s  Ziel-Saetze
 *   r  Ziel-Wiederholungen — bei t:'time' stattdessen Sekunden
 *   t  optional 'time' = Zeit-Uebung
 *   en optional englischer Name; wird unten in I18N_EN eingetragen (Display-Layer).
 *      Fehlt en, ist der Name bereits englisch/international.
 */
const EX_LIBRARY = [
  // ══ BRUST ══════════════════════════════════════════════
  {n:'Bankdrücken',            e:'', mg:'brust', s:3, r:8 },
  {n:'Schrägbankdrücken',      e:'', mg:'brust', s:3, r:10},
  {n:'Kurzhantel-Bankdrücken', e:'', mg:'brust', s:3, r:10},
  {n:'Fliegende',              e:'', mg:'brust', s:3, r:12},
  {n:'Liegestütze',            e:'', mg:'brust', s:3, r:15},
  {n:'Dips',                   e:'', mg:'brust', s:3, r:8 },
  {n:'Butterfly (Maschine)',   e:'', mg:'brust', s:3, r:12},
  {n:'Kabelzug Brust',         e:'', mg:'brust', s:3, r:12},
  {n:'Negativbankdrücken',        e:'', mg:'brust', s:3, r:10, en:'Decline Bench Press'},
  {n:'Bankdrücken (Multipresse)', e:'', mg:'brust', s:3, r:10, en:'Smith Machine Bench Press'},
  {n:'Schrägbankdrücken (Multipresse)', e:'', mg:'brust', s:3, r:10, en:'Smith Machine Incline Press'},
  {n:'Bankdrücken mit Pause',     e:'', mg:'brust', s:3, r:6,  en:'Paused Bench Press'},
  {n:'Bankdrücken (weiter Griff)',e:'', mg:'brust', s:3, r:8,  en:'Wide-Grip Bench Press'},
  {n:'Bankdrücken (Untergriff)',  e:'', mg:'brust', s:3, r:10, en:'Reverse-Grip Bench Press'},
  {n:'Bankdrücken (Bänder)',      e:'', mg:'brust', s:3, r:6,  en:'Banded Bench Press'},
  {n:'Bankdrücken (Ketten)',      e:'', mg:'brust', s:3, r:6,  en:'Chain Bench Press'},
  {n:'Board Press',               e:'', mg:'brust', s:3, r:5 },
  {n:'Floor Press',               e:'', mg:'brust', s:3, r:8 },
  {n:'Larsen Press',              e:'', mg:'brust', s:3, r:8 },
  {n:'Spoto Press',               e:'', mg:'brust', s:3, r:6 },
  {n:'Einarmiges KH-Bankdrücken', e:'', mg:'brust', s:3, r:10, en:'Single-Arm Dumbbell Press'},
  {n:'Schrägbankdrücken (KH)',    e:'', mg:'brust', s:3, r:10, en:'Incline Dumbbell Press'},
  {n:'Negativbankdrücken (KH)',   e:'', mg:'brust', s:3, r:10, en:'Decline Dumbbell Press'},
  {n:'Fliegende (Schrägbank)',    e:'', mg:'brust', s:3, r:12, en:'Incline Dumbbell Fly'},
  {n:'Fliegende (Negativbank)',   e:'', mg:'brust', s:3, r:12, en:'Decline Dumbbell Fly'},
  {n:'Fliegende am Boden',        e:'', mg:'brust', s:3, r:12, en:'Floor Fly'},
  {n:'Squeeze Press',             e:'', mg:'brust', s:3, r:12},
  {n:'Svend Press',               e:'', mg:'brust', s:3, r:15},
  {n:'KH-Überzüge',               e:'', mg:'brust', s:3, r:12, en:'Dumbbell Pullover'},
  {n:'Kabelzug Brust (hoch)',     e:'', mg:'brust', s:3, r:12, en:'High Cable Fly'},
  {n:'Kabelzug Brust (tief)',     e:'', mg:'brust', s:3, r:12, en:'Low Cable Fly'},
  {n:'Kabel-Crossover',           e:'', mg:'brust', s:3, r:12, en:'Cable Crossover'},
  {n:'Kabel-Brustpresse',         e:'', mg:'brust', s:3, r:12, en:'Cable Chest Press'},
  {n:'Einarmiger Kabelzug Brust', e:'', mg:'brust', s:3, r:12, en:'Single-Arm Cable Fly'},
  {n:'Brustpresse (Maschine)',    e:'', mg:'brust', s:3, r:12, en:'Chest Press (Machine)'},
  {n:'Schräg-Brustpresse (Maschine)', e:'', mg:'brust', s:3, r:12, en:'Incline Chest Press (Machine)'},
  {n:'Hammer-Strength-Brustpresse',   e:'', mg:'brust', s:3, r:10, en:'Hammer Strength Chest Press'},
  {n:'Landmine-Drücken',          e:'', mg:'brust', s:3, r:10, en:'Landmine Press'},
  {n:'Liegestütze (breit)',       e:'', mg:'brust', s:3, r:15, en:'Wide Push-Ups'},
  {n:'Liegestütze (erhöht)',      e:'', mg:'brust', s:3, r:15, en:'Incline Push-Ups'},
  {n:'Liegestütze (Füße erhöht)', e:'', mg:'brust', s:3, r:12, en:'Decline Push-Ups'},
  {n:'Liegestütze (Ringe)',       e:'', mg:'brust', s:3, r:10, en:'Ring Push-Ups'},
  {n:'Archer-Liegestütze',        e:'', mg:'brust', s:3, r:8,  en:'Archer Push-Ups'},
  {n:'Plyo-Liegestütze',          e:'', mg:'brust', s:3, r:8,  en:'Plyometric Push-Ups'},
  {n:'Klatsch-Liegestütze',       e:'', mg:'brust', s:3, r:6,  en:'Clap Push-Ups'},
  {n:'Hindu-Liegestütze',         e:'', mg:'brust', s:3, r:10, en:'Hindu Push-Ups'},
  {n:'Liegestütze (Bänder)',      e:'', mg:'brust', s:3, r:12, en:'Banded Push-Ups'},
  {n:'Dips (Ringe)',              e:'', mg:'brust', s:3, r:8,  en:'Ring Dips'},
  {n:'Dips (breit)',              e:'', mg:'brust', s:3, r:10, en:'Wide Dips'},
  {n:'Dips (Maschine)',           e:'', mg:'brust', s:3, r:10, en:'Assisted Dips (Machine)'},
  {n:'Medizinball-Wurf (Brust)',  e:'', mg:'brust', s:3, r:10, en:'Med Ball Chest Pass'},
  {n:'Liegestütz-Halten',         e:'', mg:'brust', s:3, r:30, t:'time', en:'Push-Up Hold'},
  {n:'Isometrische Brustpresse',  e:'', mg:'brust', s:3, r:30, t:'time', en:'Isometric Chest Squeeze'},

  // ══ RÜCKEN ═════════════════════════════════════════════
  {n:'Klimmzüge',              e:'', mg:'ruecken', s:3, r:8 },
  {n:'Latzug',                 e:'', mg:'ruecken', s:3, r:10},
  {n:'Rudern (Langhantel)',    e:'', mg:'ruecken', s:3, r:8 },
  {n:'Kurzhantel-Rudern',      e:'', mg:'ruecken', s:3, r:10},
  {n:'T-Bar Rudern',           e:'', mg:'ruecken', s:3, r:10},
  {n:'Kreuzheben',             e:'', mg:'ruecken', s:3, r:5 },
  {n:'Rumänisches Kreuzheben', e:'', mg:'ruecken', s:3, r:8 },
  {n:'Hyperextensions',        e:'', mg:'ruecken', s:3, r:15},
  {n:'Face Pulls',             e:'', mg:'ruecken', s:3, r:15},
  {n:'Pullover',               e:'', mg:'ruecken', s:3, r:12},
  {n:'Klimmzüge (breit)',      e:'', mg:'ruecken', s:3, r:8,  en:'Wide-Grip Pull-Ups'},
  {n:'Klimmzüge (eng)',        e:'', mg:'ruecken', s:3, r:8,  en:'Close-Grip Pull-Ups'},
  {n:'Klimmzüge (neutral)',    e:'', mg:'ruecken', s:3, r:8,  en:'Neutral-Grip Pull-Ups'},
  {n:'Chin-Ups (Untergriff)',  e:'', mg:'ruecken', s:3, r:8,  en:'Chin-Ups'},
  {n:'Gewichtete Klimmzüge',   e:'', mg:'ruecken', s:4, r:5,  en:'Weighted Pull-Ups'},
  {n:'Klimmzüge (Maschine)',   e:'', mg:'ruecken', s:3, r:10, en:'Assisted Pull-Ups'},
  {n:'Klimmzüge (Band)',       e:'', mg:'ruecken', s:3, r:10, en:'Band-Assisted Pull-Ups'},
  {n:'Negativ-Klimmzüge',      e:'', mg:'ruecken', s:3, r:5,  en:'Negative Pull-Ups'},
  {n:'Kommando-Klimmzüge',     e:'', mg:'ruecken', s:3, r:8,  en:'Commando Pull-Ups'},
  {n:'Muscle-Up',              e:'', mg:'ruecken', s:4, r:3 },
  {n:'Australische Klimmzüge', e:'', mg:'ruecken', s:3, r:12, en:'Inverted Rows'},
  {n:'Ring-Rudern',            e:'', mg:'ruecken', s:3, r:12, en:'Ring Rows'},
  {n:'Scapula Pull-Ups',       e:'', mg:'ruecken', s:3, r:10, en:'Scapular Pull-Ups'},
  {n:'Latzug (eng)',           e:'', mg:'ruecken', s:3, r:12, en:'Close-Grip Lat Pulldown'},
  {n:'Latzug (Untergriff)',    e:'', mg:'ruecken', s:3, r:12, en:'Reverse-Grip Lat Pulldown'},
  {n:'Latzug (neutral)',       e:'', mg:'ruecken', s:3, r:12, en:'Neutral-Grip Lat Pulldown'},
  {n:'Einarmiger Latzug',      e:'', mg:'ruecken', s:3, r:12, en:'Single-Arm Lat Pulldown'},
  {n:'Latzug (Seil)',          e:'', mg:'ruecken', s:3, r:12, en:'Rope Lat Pulldown'},
  {n:'Latzug hinter den Kopf', e:'', mg:'ruecken', s:3, r:12, en:'Behind-the-Neck Pulldown'},
  {n:'Überzüge am Kabel',      e:'', mg:'ruecken', s:3, r:12, en:'Straight-Arm Pulldown'},
  {n:'Kabel-Pullover',         e:'', mg:'ruecken', s:3, r:12, en:'Cable Pullover'},
  {n:'Rudern (Untergriff)',    e:'', mg:'ruecken', s:3, r:10, en:'Underhand Barbell Row'},
  {n:'Pendlay-Rudern',         e:'', mg:'ruecken', s:4, r:6,  en:'Pendlay Row'},
  {n:'Kabelrudern sitzend',    e:'', mg:'ruecken', s:3, r:12, en:'Seated Cable Row'},
  {n:'Kabelrudern (eng)',      e:'', mg:'ruecken', s:3, r:12, en:'Close-Grip Cable Row'},
  {n:'Kabelrudern (breit)',    e:'', mg:'ruecken', s:3, r:12, en:'Wide-Grip Cable Row'},
  {n:'Einarmiges Kabelrudern', e:'', mg:'ruecken', s:3, r:12, en:'Single-Arm Cable Row'},
  {n:'Stehendes Kabelrudern',  e:'', mg:'ruecken', s:3, r:12, en:'Standing Cable Row'},
  {n:'Maschinen-Rudern',       e:'', mg:'ruecken', s:3, r:12, en:'Machine Row'},
  {n:'Hammer-Strength-Rudern', e:'', mg:'ruecken', s:3, r:10, en:'Hammer Strength Row'},
  {n:'Brustgestütztes Rudern', e:'', mg:'ruecken', s:3, r:12, en:'Chest-Supported Row'},
  {n:'Seal Row',               e:'', mg:'ruecken', s:3, r:12},
  {n:'Landmine-Rudern',        e:'', mg:'ruecken', s:3, r:10, en:'Landmine Row'},
  {n:'Meadows-Rudern',         e:'', mg:'ruecken', s:3, r:10, en:'Meadows Row'},
  {n:'Renegade-Rudern',        e:'', mg:'ruecken', s:3, r:10, en:'Renegade Row'},
  {n:'Kroc-Rudern',            e:'', mg:'ruecken', s:3, r:15, en:'Kroc Row'},
  {n:'Gorilla-Rudern',         e:'', mg:'ruecken', s:3, r:12, en:'Gorilla Row'},
  {n:'Rudern (Multipresse)',   e:'', mg:'ruecken', s:3, r:10, en:'Smith Machine Row'},
  {n:'Sumo-Kreuzheben',        e:'', mg:'ruecken', s:3, r:5,  en:'Sumo Deadlift'},
  {n:'Trap-Bar-Kreuzheben',    e:'',  mg:'ruecken', s:3, r:6,  en:'Trap Bar Deadlift'},
  {n:'Deficit-Kreuzheben',     e:'', mg:'ruecken', s:3, r:5,  en:'Deficit Deadlift'},
  {n:'Rack Pulls',             e:'', mg:'ruecken', s:3, r:6 },
  {n:'Kreuzheben mit Pause',   e:'', mg:'ruecken', s:3, r:4,  en:'Paused Deadlift'},
  {n:'Gestrecktes Kreuzheben', e:'', mg:'ruecken', s:3, r:8,  en:'Stiff-Leg Deadlift'},
  {n:'Snatch-Grip-Kreuzheben', e:'', mg:'ruecken', s:3, r:6,  en:'Snatch-Grip Deadlift'},
  {n:'Rumänisches Kreuzheben (KH)', e:'', mg:'ruecken', s:3, r:10, en:'Dumbbell Romanian Deadlift'},
  {n:'Einbeiniges Kreuzheben', e:'', mg:'ruecken', s:3, r:10, en:'Single-Leg Deadlift'},
  {n:'Good Mornings',          e:'', mg:'ruecken', s:3, r:10},
  {n:'Reverse Hyperextensions',e:'', mg:'ruecken', s:3, r:15},
  {n:'Rückenstrecker (Maschine)', e:'', mg:'ruecken', s:3, r:15, en:'Back Extension (Machine)'},
  {n:'Superman',               e:'', mg:'ruecken', s:3, r:30, t:'time'},
  {n:'Face Pulls (Band)',      e:'', mg:'ruecken', s:3, r:20, en:'Band Face Pulls'},
  {n:'Toter Hang',             e:'', mg:'ruecken', s:3, r:30, t:'time', en:'Dead Hang'},
  // ══ BEINE ══════════════════════════════════════════════
  {n:'Kniebeugen',             e:'', mg:'beine', s:3, r:8 },
  {n:'Front-Kniebeuge',        e:'', mg:'beine', s:3, r:8 },
  {n:'Beinpresse',             e:'', mg:'beine', s:3, r:10},
  {n:'Ausfallschritte',        e:'', mg:'beine', s:3, r:12},
  {n:'Bulgarian Split Squats', e:'', mg:'beine', s:3, r:10},
  {n:'Beinstrecker',           e:'', mg:'beine', s:3, r:12},
  {n:'Beinbeuger',             e:'', mg:'beine', s:3, r:12},
  {n:'Wadenheben',             e:'', mg:'beine', s:3, r:15},
  {n:'Hip Thrust',             e:'', mg:'beine', s:3, r:10},
  {n:'Goblet Squat',           e:'', mg:'beine', s:3, r:12},
  {n:'Highbar-Kniebeuge',      e:'', mg:'beine', s:3, r:8,  en:'High-Bar Squat'},
  {n:'Lowbar-Kniebeuge',       e:'', mg:'beine', s:3, r:5,  en:'Low-Bar Squat'},
  {n:'Pausen-Kniebeuge',       e:'', mg:'beine', s:3, r:6,  en:'Paused Squat'},
  {n:'Box-Kniebeuge',          e:'', mg:'beine', s:3, r:6,  en:'Box Squat'},
  {n:'Kniebeuge (Multipresse)',e:'', mg:'beine', s:3, r:10, en:'Smith Machine Squat'},
  {n:'Hackenschmidt-Kniebeuge',e:'', mg:'beine', s:3, r:10, en:'Hack Squat'},
  {n:'Sissy-Kniebeuge',        e:'', mg:'beine', s:3, r:12, en:'Sissy Squat'},
  {n:'Zercher-Kniebeuge',      e:'', mg:'beine', s:3, r:8,  en:'Zercher Squat'},
  {n:'Überkopf-Kniebeuge',     e:'', mg:'beine', s:3, r:8,  en:'Overhead Squat'},
  {n:'Kniebeuge (Bänder)',     e:'', mg:'beine', s:3, r:6,  en:'Banded Squat'},
  {n:'Sumo-Kniebeuge',         e:'', mg:'beine', s:3, r:10, en:'Sumo Squat'},
  {n:'Cossack-Kniebeuge',      e:'', mg:'beine', s:3, r:10, en:'Cossack Squat'},
  {n:'Pistol Squat',           e:'', mg:'beine', s:3, r:6 },
  {n:'Split Squat',            e:'', mg:'beine', s:3, r:10},
  {n:'Landmine-Kniebeuge',     e:'', mg:'beine', s:3, r:10, en:'Landmine Squat'},
  {n:'Belt Squat',             e:'', mg:'beine', s:3, r:12},
  {n:'Luftkniebeugen',         e:'', mg:'beine', s:3, r:20, en:'Bodyweight Squats'},
  {n:'Sprungkniebeugen',       e:'', mg:'beine', s:3, r:10, en:'Jump Squats'},
  {n:'Wandsitz',               e:'', mg:'beine', s:3, r:45, t:'time', en:'Wall Sit'},
  {n:'Ausfallschritte (KH)',   e:'', mg:'beine', s:3, r:12, en:'Dumbbell Lunges'},
  {n:'Gehende Ausfallschritte',e:'', mg:'beine', s:3, r:20, en:'Walking Lunges'},
  {n:'Rückwärts-Ausfallschritte', e:'', mg:'beine', s:3, r:12, en:'Reverse Lunges'},
  {n:'Seitliche Ausfallschritte', e:'', mg:'beine', s:3, r:12, en:'Lateral Lunges'},
  {n:'Curtsy Lunges',          e:'', mg:'beine', s:3, r:12},
  {n:'Deficit-Ausfallschritte',e:'', mg:'beine', s:3, r:10, en:'Deficit Lunges'},
  {n:'Ausfallschritt-Sprünge', e:'', mg:'beine', s:3, r:12, en:'Jumping Lunges'},
  {n:'Beinpresse (enger Stand)',e:'', mg:'beine', s:3, r:12, en:'Close-Stance Leg Press'},
  {n:'Beinpresse (breiter Stand)', e:'', mg:'beine', s:3, r:12, en:'Wide-Stance Leg Press'},
  {n:'Beinpresse (hoher Stand)',e:'', mg:'beine', s:3, r:12, en:'High-Foot Leg Press'},
  {n:'Einbeinige Beinpresse',  e:'', mg:'beine', s:3, r:12, en:'Single-Leg Press'},
  {n:'Beinbeuger liegend',     e:'', mg:'beine', s:3, r:12, en:'Lying Leg Curl'},
  {n:'Beinbeuger sitzend',     e:'', mg:'beine', s:3, r:12, en:'Seated Leg Curl'},
  {n:'Einbeiniger Beinbeuger', e:'', mg:'beine', s:3, r:12, en:'Single-Leg Curl'},
  {n:'Nordic Curls',           e:'', mg:'beine', s:3, r:6 },
  {n:'Glute-Ham-Raise',        e:'', mg:'beine', s:3, r:10, en:'Glute Ham Raise'},
  {n:'Reverse Nordics',        e:'', mg:'beine', s:3, r:10, en:'Reverse Nordic Curl'},
  {n:'Beinstrecker einbeinig', e:'', mg:'beine', s:3, r:12, en:'Single-Leg Extension'},
  {n:'Hip Thrust (KH)',        e:'', mg:'beine', s:3, r:12, en:'Dumbbell Hip Thrust'},
  {n:'Hip Thrust (Maschine)',  e:'', mg:'beine', s:3, r:12, en:'Machine Hip Thrust'},
  {n:'Einbeiniger Hip Thrust', e:'', mg:'beine', s:3, r:12, en:'Single-Leg Hip Thrust'},
  {n:'Beckenheben',            e:'', mg:'beine', s:3, r:15, en:'Glute Bridge'},
  {n:'Frog Pumps',             e:'', mg:'beine', s:3, r:20},
  {n:'Kickbacks am Kabel',     e:'', mg:'beine', s:3, r:15, en:'Cable Glute Kickbacks'},
  {n:'Abduktoren-Maschine',    e:'', mg:'beine', s:3, r:15, en:'Hip Abduction (Machine)'},
  {n:'Adduktoren-Maschine',    e:'', mg:'beine', s:3, r:15, en:'Hip Adduction (Machine)'},
  {n:'Abduktion am Kabel',     e:'', mg:'beine', s:3, r:15, en:'Cable Hip Abduction'},
  {n:'Step-Ups',               e:'', mg:'beine', s:3, r:12},
  {n:'Step-Ups (hoch)',        e:'', mg:'beine', s:3, r:10, en:'High Step-Ups'},
  {n:'Kastensprünge',          e:'', mg:'beine', s:3, r:8,  en:'Box Jumps'},
  {n:'Schlittenschieben',      e:'', mg:'beine', s:3, r:30, t:'time', en:'Sled Push'},
  {n:'Schlittenziehen',        e:'', mg:'beine', s:3, r:30, t:'time', en:'Sled Pull'},
  {n:'Kettlebell Swings',      e:'', mg:'beine', s:3, r:15},
  {n:'Wadenheben stehend',     e:'', mg:'beine', s:4, r:15, en:'Standing Calf Raise'},
  {n:'Wadenheben sitzend',     e:'', mg:'beine', s:4, r:15, en:'Seated Calf Raise'},
  {n:'Wadenheben (Beinpresse)',e:'', mg:'beine', s:4, r:15, en:'Calf Press (Leg Press)'},
  {n:'Wadenheben einbeinig',   e:'', mg:'beine', s:3, r:15, en:'Single-Leg Calf Raise'},
  {n:'Eselwadenheben',         e:'', mg:'beine', s:3, r:15, en:'Donkey Calf Raise'},
  {n:'Wadenheben (Multipresse)',e:'', mg:'beine', s:4, r:15, en:'Smith Machine Calf Raise'},
  {n:'Tibialis-Raises',        e:'', mg:'beine', s:3, r:20, en:'Tibialis Raises'},
  {n:'Rad fahren',             e:'', mg:'beine', s:1, r:1500, t:'time'},

  // ══ SCHULTERN ══════════════════════════════════════════
  {n:'Schulterdrücken',        e:'', mg:'schultern', s:3, r:8 },
  {n:'KH-Schulterdrücken',     e:'', mg:'schultern', s:3, r:10},
  {n:'Seitheben',              e:'', mg:'schultern', s:3, r:12},
  {n:'Frontheben',             e:'', mg:'schultern', s:3, r:12},
  {n:'Reverse Flys',           e:'', mg:'schultern', s:3, r:12},
  {n:'Aufrechtes Rudern',      e:'', mg:'schultern', s:3, r:10},
  {n:'Arnold Press',           e:'', mg:'schultern', s:3, r:10},
  {n:'Shrugs',                 e:'', mg:'schultern', s:3, r:12},
  {n:'Schulterdrücken sitzend',e:'', mg:'schultern', s:3, r:10, en:'Seated Overhead Press'},
  {n:'Schulterdrücken (Multipresse)', e:'', mg:'schultern', s:3, r:10, en:'Smith Machine Shoulder Press'},
  {n:'Nackendrücken',          e:'', mg:'schultern', s:3, r:10, en:'Behind-the-Neck Press'},
  {n:'Schulterpresse (Maschine)', e:'', mg:'schultern', s:3, r:12, en:'Shoulder Press (Machine)'},
  {n:'Einarmiges Schulterdrücken', e:'', mg:'schultern', s:3, r:10, en:'Single-Arm Overhead Press'},
  {n:'Push Press',             e:'', mg:'schultern', s:4, r:5 },
  {n:'Push Jerk',              e:'', mg:'schultern', s:4, r:3 },
  {n:'Z-Press',                e:'', mg:'schultern', s:3, r:8 },
  {n:'Bradford Press',         e:'', mg:'schultern', s:3, r:12},
  {n:'Kubanisches Drücken',    e:'', mg:'schultern', s:3, r:12, en:'Cuban Press'},
  {n:'Landmine-Schulterdrücken', e:'', mg:'schultern', s:3, r:10, en:'Landmine Shoulder Press'},
  {n:'Handstand-Liegestütze',  e:'', mg:'schultern', s:3, r:6,  en:'Handstand Push-Ups'},
  {n:'Pike-Liegestütze',       e:'', mg:'schultern', s:3, r:10, en:'Pike Push-Ups'},
  {n:'Seitheben (Kabel)',      e:'', mg:'schultern', s:3, r:15, en:'Cable Lateral Raise'},
  {n:'Seitheben (Maschine)',   e:'', mg:'schultern', s:3, r:15, en:'Machine Lateral Raise'},
  {n:'Seitheben liegend',      e:'', mg:'schultern', s:3, r:15, en:'Lying Lateral Raise'},
  {n:'Seitheben (angelehnt)',  e:'', mg:'schultern', s:3, r:15, en:'Leaning Lateral Raise'},
  {n:'Seitheben (Band)',       e:'', mg:'schultern', s:3, r:20, en:'Band Lateral Raise'},
  {n:'Frontheben (Kabel)',     e:'', mg:'schultern', s:3, r:12, en:'Cable Front Raise'},
  {n:'Frontheben (Scheibe)',   e:'', mg:'schultern', s:3, r:12, en:'Plate Front Raise'},
  {n:'Reverse Flys (Kabel)',   e:'', mg:'schultern', s:3, r:15, en:'Cable Reverse Fly'},
  {n:'Reverse Flys (Maschine)',e:'', mg:'schultern', s:3, r:15, en:'Reverse Pec Deck'},
  {n:'Bandzug auseinander',    e:'', mg:'schultern', s:3, r:20, en:'Band Pull-Aparts'},
  {n:'Y-Raises',               e:'', mg:'schultern', s:3, r:15},
  {n:'Powell Raise',           e:'', mg:'schultern', s:3, r:12},
  {n:'Aufrechtes Rudern (Kabel)', e:'', mg:'schultern', s:3, r:12, en:'Cable Upright Row'},
  {n:'Aufrechtes Rudern (KH)', e:'', mg:'schultern', s:3, r:12, en:'Dumbbell Upright Row'},
  {n:'Langhantel-Highpull',    e:'', mg:'schultern', s:4, r:6,  en:'Barbell High Pull'},
  {n:'Shrugs (KH)',            e:'', mg:'schultern', s:3, r:15, en:'Dumbbell Shrugs'},
  {n:'Shrugs (Kabel)',         e:'', mg:'schultern', s:3, r:15, en:'Cable Shrugs'},
  {n:'Shrugs (Maschine)',      e:'', mg:'schultern', s:3, r:15, en:'Machine Shrugs'},
  {n:'Shrugs (Trap Bar)',      e:'',  mg:'schultern', s:3, r:15, en:'Trap Bar Shrugs'},
  {n:'Überkopf-Shrugs',        e:'', mg:'schultern', s:3, r:12, en:'Overhead Shrugs'},
  {n:'Außenrotation',          e:'', mg:'schultern', s:3, r:15, en:'External Rotation'},
  {n:'Innenrotation',          e:'', mg:'schultern', s:3, r:15, en:'Internal Rotation'},
  {n:'Schulterrotation (Kabel)', e:'', mg:'schultern', s:3, r:15, en:'Cable Shoulder Rotation'},
  {n:'Schulterkreisen',        e:'', mg:'schultern', s:2, r:45, t:'time', en:'Arm Circles'},
  {n:'Überkopf-Halten',        e:'', mg:'schultern', s:3, r:30, t:'time', en:'Overhead Hold'},
  {n:'Kellner-Gang',           e:'', mg:'schultern', s:3, r:40, t:'time', en:'Waiter Walk'},
  // ══ ARME ═══════════════════════════════════════════════
  {n:'Bizeps-Curls (KH)',      e:'', mg:'arme', s:3, r:10},
  {n:'Bizeps-Curls (LH)',      e:'', mg:'arme', s:3, r:10},
  {n:'Hammer-Curls',           e:'', mg:'arme', s:3, r:10},
  {n:'Konzentrations-Curls',   e:'', mg:'arme', s:3, r:12},
  {n:'Trizeps-Dips',           e:'', mg:'arme', s:3, r:10},
  {n:'Trizepsdrücken (Kabel)', e:'', mg:'arme', s:3, r:12},
  {n:'French Press',           e:'', mg:'arme', s:3, r:10},
  {n:'Engers Bankdrücken',     e:'', mg:'arme', s:3, r:8 },
  {n:'Preacher Curls',         e:'', mg:'arme', s:3, r:10},
  {n:'Unterarm-Curls',         e:'', mg:'arme', s:3, r:15},
  {n:'Bizeps-Curls (SZ-Stange)', e:'', mg:'arme', s:3, r:10, en:'EZ-Bar Curls'},
  {n:'Schrägbank-Curls',       e:'', mg:'arme', s:3, r:12, en:'Incline Dumbbell Curls'},
  {n:'Spider-Curls',           e:'', mg:'arme', s:3, r:12, en:'Spider Curls'},
  {n:'Drag Curls',             e:'', mg:'arme', s:3, r:12},
  {n:'Zottman-Curls',          e:'', mg:'arme', s:3, r:12, en:'Zottman Curls'},
  {n:'21er-Curls',             e:'', mg:'arme', s:3, r:21, en:'21s'},
  {n:'Kabel-Curls',            e:'', mg:'arme', s:3, r:12, en:'Cable Curls'},
  {n:'Kabel-Curls (Seil)',     e:'', mg:'arme', s:3, r:12, en:'Rope Cable Curls'},
  {n:'Einarmige Kabel-Curls',  e:'', mg:'arme', s:3, r:12, en:'Single-Arm Cable Curls'},
  {n:'Bayesian-Curls',         e:'', mg:'arme', s:3, r:12, en:'Bayesian Cable Curls'},
  {n:'Preacher Curls (Maschine)', e:'', mg:'arme', s:3, r:12, en:'Machine Preacher Curls'},
  {n:'Preacher Hammer-Curls',  e:'', mg:'arme', s:3, r:12, en:'Preacher Hammer Curls'},
  {n:'Hammer-Curls (Seil)',    e:'', mg:'arme', s:3, r:12, en:'Rope Hammer Curls'},
  {n:'Schrägbank-Hammer-Curls',e:'', mg:'arme', s:3, r:12, en:'Incline Hammer Curls'},
  {n:'Cross-Body-Curls',       e:'', mg:'arme', s:3, r:12, en:'Cross-Body Curls'},
  {n:'Reverse Curls',          e:'', mg:'arme', s:3, r:12, en:'Reverse Curls'},
  {n:'Reverse Curls (SZ-Stange)', e:'', mg:'arme', s:3, r:12, en:'EZ-Bar Reverse Curls'},
  {n:'Bizeps-Curls (Band)',    e:'', mg:'arme', s:3, r:15, en:'Band Curls'},
  {n:'Isometrische Curls',     e:'', mg:'arme', s:3, r:30, t:'time', en:'Isometric Curl Hold'},
  {n:'Trizepsdrücken (Seil)',  e:'', mg:'arme', s:3, r:12, en:'Rope Pushdown'},
  {n:'Trizepsdrücken (Stange)',e:'', mg:'arme', s:3, r:12, en:'Bar Pushdown'},
  {n:'Trizepsdrücken (Untergriff)', e:'', mg:'arme', s:3, r:12, en:'Reverse-Grip Pushdown'},
  {n:'Einarmiges Trizepsdrücken', e:'', mg:'arme', s:3, r:12, en:'Single-Arm Pushdown'},
  {n:'Überkopf-Trizepsdrücken',e:'', mg:'arme', s:3, r:12, en:'Overhead Triceps Extension'},
  {n:'Überkopf-Trizepsdrücken (Seil)', e:'', mg:'arme', s:3, r:12, en:'Overhead Rope Extension'},
  {n:'KH-Trizepsdrücken über Kopf', e:'', mg:'arme', s:3, r:12, en:'Dumbbell Overhead Extension'},
  {n:'Trizeps-Kickbacks',      e:'', mg:'arme', s:3, r:15, en:'Triceps Kickbacks'},
  {n:'Trizeps-Kickbacks (Kabel)', e:'', mg:'arme', s:3, r:15, en:'Cable Triceps Kickbacks'},
  {n:'Skull Crushers (KH)',    e:'', mg:'arme', s:3, r:12, en:'Dumbbell Skull Crushers'},
  {n:'JM Press',               e:'', mg:'arme', s:3, r:10},
  {n:'Tate Press',             e:'', mg:'arme', s:3, r:12},
  {n:'California Press',       e:'', mg:'arme', s:3, r:10},
  {n:'Bankdips',               e:'', mg:'arme', s:3, r:15, en:'Bench Dips'},
  {n:'Diamant-Liegestütze',    e:'', mg:'arme', s:3, r:12, en:'Diamond Push-Ups'},
  {n:'Trizepsdrücken (Maschine)', e:'', mg:'arme', s:3, r:12, en:'Triceps Extension (Machine)'},
  {n:'Trizepsdrücken (Band)',  e:'', mg:'arme', s:3, r:15, en:'Band Pushdown'},
  {n:'Reverse Unterarm-Curls', e:'', mg:'arme', s:3, r:15, en:'Reverse Wrist Curls'},
  {n:'Unterarm-Curls hinter dem Rücken', e:'', mg:'arme', s:3, r:15, en:'Behind-the-Back Wrist Curls'},
  {n:'Handgelenks-Roller',     e:'', mg:'arme', s:3, r:5,  en:'Wrist Roller'},
  {n:'Scheiben-Halten',        e:'', mg:'arme', s:3, r:30, t:'time', en:'Plate Pinch'},
  {n:'Farmers Walk',           e:'', mg:'arme', s:3, r:40, t:'time'},
  {n:'Handtrainer',            e:'', mg:'arme', s:3, r:20, en:'Hand Gripper'},

  // ══ CORE ═══════════════════════════════════════════════
  {n:'Plank',                  e:'', mg:'core', s:3, r:60, t:'time'},
  {n:'Seitlicher Plank',       e:'', mg:'core', s:3, r:45, t:'time'},
  {n:'Crunches',               e:'', mg:'core', s:3, r:20},
  {n:'Beinheben',              e:'', mg:'core', s:3, r:12},
  {n:'Russian Twists',         e:'', mg:'core', s:3, r:20},
  {n:'Mountain Climbers',      e:'', mg:'core', s:3, r:30, t:'time'},
  {n:'Hollow Hold',            e:'', mg:'core', s:3, r:30, t:'time'},
  {n:'Cable Crunches',         e:'', mg:'core', s:3, r:15},
  {n:'Käfer',                  e:'', mg:'core', s:3, r:20},
  {n:'Hängendes Beinheben',    e:'', mg:'core', s:3, r:10},
  {n:'Sit-Ups',                e:'', mg:'core', s:3, r:20},
  {n:'Sit-Ups (Negativbank)',  e:'', mg:'core', s:3, r:15, en:'Decline Sit-Ups'},
  {n:'Schräge Crunches',       e:'', mg:'core', s:3, r:20, en:'Oblique Crunches'},
  {n:'Reverse Crunches',       e:'', mg:'core', s:3, r:15, en:'Reverse Crunches'},
  {n:'Bicycle Crunches',       e:'', mg:'core', s:3, r:20},
  {n:'Crunches (Maschine)',    e:'', mg:'core', s:3, r:15, en:'Ab Crunch Machine'},
  {n:'V-Ups',                  e:'', mg:'core', s:3, r:15},
  {n:'Jackknife Sit-Ups',      e:'', mg:'core', s:3, r:15},
  {n:'Toes to Bar',            e:'', mg:'core', s:3, r:10},
  {n:'Hängendes Knieheben',    e:'', mg:'core', s:3, r:15, en:'Hanging Knee Raises'},
  {n:'Liegendes Beinheben',    e:'', mg:'core', s:3, r:15, en:'Lying Leg Raises'},
  {n:'Scherenschlag',          e:'', mg:'core', s:3, r:30, t:'time', en:'Flutter Kicks'},
  {n:'Ab-Rollout',             e:'', mg:'core', s:3, r:10, en:'Ab Wheel Rollout'},
  {n:'Rollout mit Langhantel', e:'', mg:'core', s:3, r:10, en:'Barbell Rollout'},
  {n:'Plank mit Schulter-Tap', e:'', mg:'core', s:3, r:20, en:'Plank Shoulder Taps'},
  {n:'Plank Jacks',            e:'', mg:'core', s:3, r:30, t:'time'},
  {n:'Copenhagen Plank',       e:'', mg:'core', s:3, r:30, t:'time'},
  {n:'Reverse Plank',          e:'', mg:'core', s:3, r:30, t:'time'},
  {n:'Body Saw',               e:'', mg:'core', s:3, r:12},
  {n:'Stir the Pot',           e:'', mg:'core', s:3, r:20},
  {n:'Pallof Press',           e:'', mg:'core', s:3, r:12},
  {n:'Wood Chop (Kabel)',      e:'', mg:'core', s:3, r:15, en:'Cable Wood Chop'},
  {n:'Rumpfrotation (Maschine)', e:'', mg:'core', s:3, r:15, en:'Torso Rotation Machine'},
  {n:'Seitbeugen (KH)',        e:'', mg:'core', s:3, r:15, en:'Dumbbell Side Bends'},
  {n:'Seitbeugen (Kabel)',     e:'', mg:'core', s:3, r:15, en:'Cable Side Bends'},
  {n:'Medizinball-Slam',       e:'', mg:'core', s:3, r:12, en:'Med Ball Slam'},
  {n:'Medizinball-Twist',      e:'', mg:'core', s:3, r:20, en:'Med Ball Russian Twist'},
  {n:'Dragon Flag',            e:'', mg:'core', s:3, r:6 },
  {n:'L-Sit',                  e:'', mg:'core', s:3, r:20, t:'time'},
  {n:'Hollow Rocks',           e:'', mg:'core', s:3, r:20},
  {n:'Vogelhund',              e:'', mg:'core', s:3, r:20, en:'Bird Dog'},
  {n:'Windmühle',              e:'', mg:'core', s:3, r:10, en:'Windmill'},
  {n:'Turkish Get-Up',         e:'', mg:'core', s:3, r:5 },
  {n:'Bärengang',              e:'', mg:'core', s:3, r:30, t:'time', en:'Bear Crawl'},
  {n:'Bauch-Vakuum',           e:'', mg:'core', s:3, r:20, t:'time', en:'Stomach Vacuum'},

  // ══ CARDIO & KONDITION (ohne Muskelgruppe) ═════════════
  {n:'Laufband',               e:'', mg:'', s:1, r:1200, t:'time'},
  {n:'Seilspringen',           e:'', mg:'', s:3, r:60,  t:'time'},
  {n:'Rudern (Cardio)',        e:'', mg:'', s:1, r:1200, t:'time'},
  {n:'Crosstrainer',           e:'', mg:'', s:1, r:1200, t:'time', en:'Elliptical'},
  {n:'Stairmaster',            e:'', mg:'', s:1, r:900,  t:'time'},
  {n:'Spinning',               e:'', mg:'', s:1, r:1800, t:'time', en:'Spin Bike'},
  {n:'Assault Bike',           e:'', mg:'', s:1, r:600,  t:'time'},
  {n:'SkiErg',                 e:'', mg:'', s:1, r:600,  t:'time'},
  {n:'Laufen draußen',         e:'', mg:'', s:1, r:1800, t:'time', en:'Outdoor Run'},
  {n:'Rad fahren draußen',     e:'', mg:'', s:1, r:2700, t:'time', en:'Outdoor Cycling'},
  {n:'Gehen',                  e:'', mg:'', s:1, r:1800, t:'time', en:'Walking'},
  {n:'Gehen mit Steigung',     e:'', mg:'', s:1, r:1800, t:'time', en:'Incline Walk'},
  {n:'Wandern',                e:'', mg:'', s:1, r:3600, t:'time', en:'Hiking'},
  {n:'Treppenlauf',            e:'', mg:'', s:1, r:600,  t:'time', en:'Stair Run'},
  {n:'Schwimmen',              e:'', mg:'', s:1, r:1800, t:'time', en:'Swimming'},
  {n:'Sprints',                e:'', mg:'', s:6, r:20,   t:'time'},
  {n:'Bergsprints',            e:'', mg:'', s:6, r:20,   t:'time', en:'Hill Sprints'},
  {n:'Intervallsprints',       e:'', mg:'', s:8, r:30,   t:'time', en:'Sprint Intervals'},
  {n:'Burpees',                e:'', mg:'', s:3, r:15},
  {n:'Battle Ropes',           e:'', mg:'', s:4, r:30,   t:'time'},
  {n:'Boxsack',                e:'', mg:'', s:5, r:180,  t:'time', en:'Heavy Bag'},
  {n:'Schattenboxen',          e:'', mg:'', s:3, r:180,  t:'time', en:'Shadow Boxing'},
  {n:'Double Unders',          e:'', mg:'', s:5, r:40 },
  {n:'Hampelmänner',           e:'', mg:'', s:3, r:40,   en:'Jumping Jacks'},
  {n:'Kniehebelauf',           e:'', mg:'', s:3, r:30,   t:'time', en:'High Knees'},
  {n:'Anfersen',               e:'', mg:'', s:3, r:30,   t:'time', en:'Butt Kicks'},
  {n:'Wall Balls',             e:'', mg:'', s:4, r:15},
  {n:'Thrusters',              e:'', mg:'', s:4, r:10},
  {n:'Clean & Press',          e:'', mg:'', s:4, r:5 },
  {n:'Power Clean',            e:'', mg:'', s:5, r:3 },
  {n:'Hang Clean',             e:'', mg:'', s:5, r:3 },
  {n:'Reißen',                 e:'', mg:'', s:5, r:2,    en:'Snatch'},
  {n:'Devil Press',            e:'', mg:'', s:4, r:10},
  {n:'Man Makers',             e:'', mg:'', s:3, r:8 },
  // ══ ERGÄNZUNGEN ════════════════════════════════════════
  {n:'Guillotine Press',            e:'', mg:'brust', s:3, r:10},
  {n:'Bankdrücken (neutral, KH)',   e:'', mg:'brust', s:3, r:10, en:'Neutral-Grip Dumbbell Press'},
  {n:'Bankdrücken (Füße hoch)',     e:'', mg:'brust', s:3, r:10, en:'Feet-Up Bench Press'},
  {n:'Kettlebell-Floor-Press',      e:'', mg:'brust', s:3, r:10, en:'Kettlebell Floor Press'},
  {n:'Fliegende (Maschine, einarmig)', e:'', mg:'brust', s:3, r:12, en:'Single-Arm Pec Deck'},
  {n:'Gewichtete Dips',             e:'', mg:'brust', s:4, r:6,  en:'Weighted Dips'},
  {n:'Klimmzüge (L-Sit)',           e:'', mg:'ruecken', s:3, r:6,  en:'L-Sit Pull-Ups'},
  {n:'Rack Chins',                  e:'', mg:'ruecken', s:3, r:12},
  {n:'Kabelrudern (Untergriff)',    e:'', mg:'ruecken', s:3, r:12, en:'Underhand Cable Row'},
  {n:'Kettlebell-Rudern',           e:'', mg:'ruecken', s:3, r:12, en:'Kettlebell Row'},
  {n:'Rudern (Trap Bar)',           e:'', mg:'ruecken', s:3, r:10, en:'Trap Bar Row'},
  {n:'Kreuzheben (Multipresse)',    e:'', mg:'ruecken', s:3, r:8,  en:'Smith Machine Deadlift'},
  {n:'Block Pulls',                 e:'', mg:'ruecken', s:3, r:5 },
  {n:'Jefferson-Curl',              e:'', mg:'ruecken', s:3, r:8,  en:'Jefferson Curl'},
  {n:'Latzug (Band)',               e:'', mg:'ruecken', s:3, r:15, en:'Band Lat Pulldown'},
  {n:'Gewichtete Hyperextensions',  e:'', mg:'ruecken', s:3, r:12, en:'Weighted Back Extensions'},
  {n:'Kniebeuge (Sicherheitsstange)', e:'', mg:'beine', s:3, r:8,  en:'Safety Bar Squat'},
  {n:'Anderson-Kniebeuge',          e:'', mg:'beine', s:3, r:6,  en:'Anderson Squat'},
  {n:'Kettlebell-Kniebeuge',        e:'', mg:'beine', s:3, r:12, en:'Kettlebell Squat'},
  {n:'Beinpresse (horizontal)',     e:'', mg:'beine', s:3, r:15, en:'Horizontal Leg Press'},
  {n:'Ausfallschritte (Multipresse)', e:'', mg:'beine', s:3, r:12, en:'Smith Machine Lunges'},
  {n:'Split Squat (Multipresse)',   e:'', mg:'beine', s:3, r:10, en:'Smith Machine Split Squat'},
  {n:'Hip Thrust (Multipresse)',    e:'', mg:'beine', s:3, r:12, en:'Smith Machine Hip Thrust'},
  {n:'Wadenheben (KH)',             e:'', mg:'beine', s:4, r:15, en:'Dumbbell Calf Raise'},
  {n:'Skater-Sprünge',              e:'', mg:'beine', s:3, r:20, en:'Skater Jumps'},
  {n:'Rückwärts-Schlittenziehen',   e:'', mg:'beine', s:3, r:30, t:'time', en:'Backward Sled Drag'},
  {n:'Terminal Knee Extension',     e:'', mg:'beine', s:3, r:15},
  {n:'Hüftbeugen am Kabel',         e:'', mg:'beine', s:3, r:15, en:'Cable Hip Flexion'},
  {n:'Viking Press',                e:'', mg:'schultern', s:3, r:8 },
  {n:'Log Press',                   e:'', mg:'schultern', s:4, r:5 },
  {n:'Kettlebell-Schulterdrücken',  e:'', mg:'schultern', s:3, r:10, en:'Kettlebell Overhead Press'},
  {n:'Bottoms-Up Press',            e:'', mg:'schultern', s:3, r:8 },
  {n:'Frontheben (Seil)',           e:'', mg:'schultern', s:3, r:15, en:'Rope Front Raise'},
  {n:'Vorgebeugtes Reverse Fly',    e:'', mg:'schultern', s:3, r:15, en:'Bent-Over Reverse Fly'},
  {n:'T-Raises',                    e:'', mg:'schultern', s:3, r:15},
  {n:'W-Raises',                    e:'', mg:'schultern', s:3, r:15},
  {n:'Waiter Curl',                 e:'', mg:'arme', s:3, r:12},
  {n:'Kabel-Curls (hoch)',          e:'', mg:'arme', s:3, r:12, en:'High Cable Curl'},
  {n:'Reverse Preacher Curls',      e:'', mg:'arme', s:3, r:12},
  {n:'Scheiben-Curls',              e:'', mg:'arme', s:3, r:15, en:'Plate Curl'},
  {n:'Fat-Grip-Curls',              e:'', mg:'arme', s:3, r:12},
  {n:'Trizepsdrücken (V-Bar)',      e:'', mg:'arme', s:3, r:12, en:'V-Bar Pushdown'},
  {n:'Trizeps-Extension sitzend (SZ)', e:'', mg:'arme', s:3, r:12, en:'Seated EZ-Bar Extension'},
  {n:'Trizeps-Extension (Ringe)',   e:'', mg:'arme', s:3, r:10, en:'Ring Triceps Extension'},
  {n:'Unterarm-Curls (Kabel)',      e:'', mg:'arme', s:3, r:15, en:'Cable Wrist Curls'},
  {n:'Hängendes seitliches Beinheben', e:'', mg:'core', s:3, r:12, en:'Hanging Oblique Raises'},
  {n:'Stehender Ab-Rollout',        e:'', mg:'core', s:3, r:8,  en:'Standing Ab Wheel Rollout'},
  {n:'GHD Sit-Ups',                 e:'', mg:'core', s:3, r:15},
  {n:'Stehender Kabel-Crunch',      e:'', mg:'core', s:3, r:15, en:'Standing Cable Crunch'},
  {n:'Landmine-Twist',              e:'', mg:'core', s:3, r:15, en:'Landmine Twist'},
  {n:'Koffer-Tragen',               e:'', mg:'core', s:3, r:40, t:'time', en:'Suitcase Carry'},
  {n:'Gewichteter Plank',           e:'', mg:'core', s:3, r:45, t:'time', en:'Weighted Plank'},
  {n:'Seitlicher Plank mit Beinheben', e:'', mg:'core', s:3, r:12, en:'Side Plank Leg Raise'},
  {n:'Sit-Ups mit Rotation',        e:'', mg:'core', s:3, r:20, en:'Twisting Sit-Ups'},
  {n:'Beinheben mit Hüftschub',     e:'', mg:'core', s:3, r:12, en:'Leg Raise with Hip Lift'},
  {n:'Laufband-Intervalle',         e:'', mg:'', s:8, r:60,   t:'time', en:'Treadmill Intervals'},
  {n:'Ruder-Intervalle',            e:'', mg:'', s:8, r:60,   t:'time', en:'Rowing Intervals'},
  {n:'HIIT-Intervalle',             e:'', mg:'', s:10, r:30,  t:'time', en:'HIIT Intervals'},
  {n:'Zirkeltraining',              e:'', mg:'', s:3, r:600,  t:'time', en:'Circuit Training'},
  {n:'Sandsack-Tragen',             e:'', mg:'', s:3, r:40,   t:'time', en:'Sandbag Carry'},
  {n:'Reifen-Flippen',              e:'', mg:'', s:4, r:8,    en:'Tire Flips'},
  {n:'Vorschlaghammer',             e:'', mg:'', s:4, r:20,   en:'Sledgehammer Swings'},
  {n:'Aufwärmen',                   e:'', mg:'', s:1, r:600,  t:'time', en:'Warm-Up'},
  {n:'Cool-Down',                   e:'', mg:'', s:1, r:300,  t:'time'},
  {n:'Beweglichkeitstraining',      e:'', mg:'', s:1, r:600,  t:'time', en:'Mobility Work'},
  {n:'Dehnen',                      e:'', mg:'', s:1, r:600,  t:'time', en:'Stretching'},
];

/* ── i18n: englische Namen im Display-Layer registrieren ────────────────
 * app-i18n.js laeuft VOR dieser Datei, I18N_EN existiert also bereits.
 * Bestehende Eintraege gewinnen — handgepflegte Uebersetzungen bleiben. */
if (typeof I18N_EN === 'object' && I18N_EN) {
  for (let i = 0; i < EX_LIBRARY.length; i++) {
    const it = EX_LIBRARY[i];
    if (it.en && !I18N_EN[it.n]) I18N_EN[it.n] = it.en;
  }
}
